name: ml-pipeline-obelix
channels:
     - conda-forge
     - anaconda
     - defaults
     - rdkit
     - mordred-descriptor
dependencies:
- python=3.10.5
- ase==3.22.1
- openbabel==3.1.1
- pandas==1.4.3
- numpy==1.23.2
- rdkit==2022.09.1
- morfeus-ml==0.7.1
- mordred==1.2.0
- openpyxl
- scikit-learn
- matplotlib
- seaborn
- tpot
- xtb-python
- pip
- pip:
  - libconeangle
  - cclib
  - typing-extensions
