name: obelix-ml-pipeline
channels:
     - conda-forge
     - anaconda
     - defaults
     - rdkit
     - mordred-descriptor
dependencies:
- python=3.10.5
- pandas==1.4.3
- numpy==1.23.2
- morfeus-ml==0.7.1
- rdkit==2022.09.1
- openpyxl
- scikit-learn
- scipy
- matplotlib
- seaborn
- tpot
- xtb-python
- pip
- pip:
  - libconeangle
  - cclib
  - typing-extensions
  - notebook
  - plotly==5.14.0
  - scikit-learn-intelex
