name: obelix-ml-pipeline
channels:
     - conda-forge
     - anaconda
     - defaults
     - rdkit
dependencies:
- python=3.10.5
- pandas=1.4.3
- numpy=1.23.2
- morfeus-ml=0.7.1
- rdkit=2022.09.1
- openpyxl=3.1.1
- scikit-learn=1.3.2
- scipy=1.10.1
- matplotlib=3.7.1
- seaborn=0.12.2
- python-kaleido=0.2.1
- pip=23.0.1
- pip:
  - libconeangle==0.1.2
  - cclib==1.7.2
  - typing-extensions==4.5.0
  - ipython==8.12.0
  - notebook==6.5.3
  - traitlets==5.9.0
  - plotly==5.14.0
  - scikit-learn-intelex==2023.1.1
